services:
  # --- Infrastructure ---
  redis:
    image: redis:7-alpine
    network_mode: host

  postgres:
    image: postgres:15-alpine
    network_mode: host
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: avtomatika

  minio:
    image: minio/minio
    network_mode: host
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    network_mode: host
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://localhost:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/avtomatika-payloads || true;
      /usr/bin/mc policy set public myminio/avtomatika-payloads;
      exit 0;
      "

  jaeger:
    image: jaegertracing/all-in-one:latest
    network_mode: host

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.93.0
    network_mode: host
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "-promscrape.config=/etc/prometheus/prometheus.yml"
      - "-promscrape.configCheckInterval=10s"

  grafana:
    image: grafana/grafana:10.0.0
    network_mode: host
    volumes:
      - ./ops/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./ops/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  webhook-receiver:
    image: avtomatika-base
    build: .
    network_mode: host
    command: ["python", "webhook_receiver.py"]
    environment:
      - LOG_LEVEL=DEBUG


  # --- Avtomatika Orchestrator ---
  orchestrator:
    image: avtomatika-base
    build: .
    network_mode: host
    environment:
      - REDIS_HOST=localhost
      - HISTORY_DATABASE_URI=postgresql://user:password@localhost:5432/avtomatika
      - S3_ENDPOINT_URL=http://localhost:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_DEFAULT_BUCKET=avtomatika-payloads
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - OTEL_SERVICE_NAME=avtomatika-orchestrator
      - LOG_LEVEL=DEBUG
      - SCHEDULES_CONFIG_PATH=/app/schedules.toml
      - CLIENTS_CONFIG_PATH=/app/example_clients.toml
      - WORKERS_CONFIG_PATH=/app/example_workers.toml
      - BLUEPRINTS_DIR=/app/blueprints
    volumes:
      - ./schedules.toml:/app/schedules.toml
      - ./example_clients.toml:/app/example_clients.toml
      - ./example_workers.toml:/app/example_workers.toml
      - ./blueprints:/app/blueprints

  # --- Avtomatika Workers ---
  worker-gpu:
    image: avtomatika-base
    build: .
    network_mode: host
    command: ["python", "workers/gpu.py"]
    environment:
      - WORKER_ID=gpu-worker-01
      - WORKER_TOKEN=super-secret-gpu-worker-token
      - ORCHESTRATOR_URL=http://localhost:8080
      - CPU_CORES=8
      - RAM_GB=16
      - S3_ENDPOINT_URL=http://localhost:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_DEFAULT_BUCKET=avtomatika-payloads
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - OTEL_SERVICE_NAME=gpu-worker
      - HOSTNAME=worker-gpu-node

  worker-cpu-1:
    image: avtomatika-base
    build: .
    network_mode: host
    command: ["python", "workers/cpu_unreliable.py"]
    environment:
      - WORKER_ID=cpu-worker-01
      - WORKER_TOKEN=super-secret-cpu-worker-token
      - ORCHESTRATOR_URL=http://localhost:8080
      - CPU_CORES=4
      - RAM_GB=8
      - S3_ENDPOINT_URL=http://localhost:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_DEFAULT_BUCKET=avtomatika-payloads
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - OTEL_SERVICE_NAME=cpu-worker-unreliable
      - HOSTNAME=worker-cpu-1-node

  worker-cpu-2:
    image: avtomatika-base
    build: .
    network_mode: host
    command: ["python", "workers/cpu_reliable.py"]
    environment:
      - WORKER_ID=cpu-worker-02
      - WORKER_TOKEN=super-secret-cpu-worker-token-2
      - ORCHESTRATOR_URL=http://localhost:8080
      - CPU_CORES=4
      - RAM_GB=8
      - S3_ENDPOINT_URL=http://localhost:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_DEFAULT_BUCKET=avtomatika-payloads
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      - OTEL_SERVICE_NAME=cpu-worker-reliable
      - HOSTNAME=worker-cpu-2-node
