["gpu-worker-01"]
token = "super-secret-gpu-worker-token"

["cpu-worker-01"]
token = "super-secret-cpu-worker-token"

["cpu-worker-02"]
token = "super-secret-cpu-worker-token-2"

["secure-worker-01"]
token = "super-secret-secure-worker-token"
