[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "avtomatika-full-example"
version = "1.0b22+w1.0b14.0"
description = "Comprehensive example for Avtomatika HLNOrchestrator"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
dependencies = [
    "avtomatika[all]==1.0b22",
    "avtomatika-worker[pydantic]==1.0b14",
]

[project.optional-dependencies]
test = [
    "pytest>=9.0",
    "pytest-asyncio>=0.23",
    "ruff>=0.4",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["*.py"]
